services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    # On a retiré "ports", Caddy communiquera en réseau interne

  frontend:
    build: ./frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    # On a retiré "ports" ici aussi

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:            
      - DOMAIN=${DOMAIN}  
      - TLS_EMAIL=${TLS_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config: