services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app # Permet de modifier le code sans rebuild

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend